### ISSUE TITLE
Default Snippet need to be more userfriendly

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#230]
To activate the default snippet he need to do this int he config

```
sulu_snippet:
    types:
        snippet:
            default_enabled: true
```

Then he also need to add to his role the permissons to set Webspaces->Settings->Snippets
