### ISSUE TITLE
Document how to run preview with redis for multiple webserver support

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#378]
`app/config/admin/config_prod.yml` and `app/config/website/config_prod.yml`

```yml
sulu_preview:
    cache:
        type: redis
        redis:
            host: "%redis_host%"
            port: "%redis_port%"
            password: "%redis_password%"

sulu_websocket:
    cache:
        type: redis
        redis:
            host: "%redis_host%"
            port: "%redis_port%"
            password: "%redis_password%"
```

app/config/parameters.yml.dist

```yml
    redis_host: localhost
    redis_port: 6379
    redis_password: ''
```
